---
title: "modMetricsR vignette"
author: "Giulio Giagnoni"
date: "2023-07-03"
output: rmarkdown::html_vignette:
  toc: TRUE
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: modMetricsbib.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(modMetricsR)
```


# Package overview


## Examples


## Metrics included


$$ Residuals = Observation_i - Prediction_i $$


Mean Square Error (Bibby and Toutenburg, 1977)

$$ MSE = \frac{\sum_{n=1}{n}(Y_i-\mathbf{Y_i})^2 }{n} $$


Root Mean Square Error

$$ RMSE = \sqrt{MSE} $$


Mean Absolute Error (Chai and Draxler, 2014)

$$ MAE = \frac{\sum_{n=1}{n}|Y_i-\mathbf{Y_i}|}{n} $$


Mean Bias and Mean Bias as percentage of MSE

$$ MB =    MB% = MB/MSE*100  $$


Slope bias and Slope Bias as percentage of MSE

$$ SP =     SP% = SP/MSE*100 $$


Dispersion bias and Dispersion Bias as percentage of MSE

$$ DB =    DB% = DB/MSE*100$$



